### ISSUE TITLE
EACCESS error on loading vscode

### ISSUE THREAD

**Issue by JulianKingman** [vknabel/vscode-swift-development-environment#115]
I get the following error on VS Code startup:
```bash
Debugger listening on ws://127.0.0.1:6004/8e3e219b-922e-417d-813c-efa47c9cb1f5
For help, see: https://nodejs.org/en/docs/inspector
/Users/julian/.vscode/extensions/vknabel.vscode-swift-development-environment-2.12.2/out/sourcekites-server/sourcekites.js:55
        throw err;
        ^

Error: spawn . EACCES
    at Process.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn .',
  path: '.',
  spawnargs: []
}
[Info  - 7:42:15 AM] Connection to server got closed. Server will restart.
```

Any ideas what it's about? Thx!

**Comment by vknabel** [comment]
Hey @JulianKingman, thanks for opening an issue. 

I suppose you want to use sourcekite, right?
In which operating system do you run?

Could you also drop your configs regarding Swift?

Have you installed [sourcekite](https://github.com/vknabel/vscode-swift-development-environment#using-sourcekite), yet?

**Comment by vknabel** [comment]
Closed to to inactivity
