### ISSUE TITLE
Error: spawn ~/sourcekite/.build/x86_64-apple-macosx10.10/release ENOENT

### ISSUE THREAD

**Issue by xx-li** [vknabel/vscode-swift-development-environment#30]
### env
- mac os 10.13.4
- xcode 9.4.1
- vs code 1.24.1

when open swift file, appear error:

```
/Users/lixinxing/.vscode/extensions/vknabel.vscode-swift-development-environment-2.4.3/out/src/server/sourcekites.js:54
        throw err;
        ^

Error: spawn ~/sourcekite/.build/x86_64-apple-macosx10.10/release ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Info  - 16:50:32] Connection to server got closed. Server will restart.
```

**Comment by vknabel** [comment]
Did you set the sourcekite path to `/Users/lixinxing/sourcekite/.build/x86_64-apple-macosx10.10/release/sourcekite` or `~/sourcekite/.build/x86_64-apple-macosx10.10/release`?

The path must be absolute (use `/Users/lixinxing` instead of `~`) and it must include the name of the compiled executable (e.g. `release/sourcekite`)

If the doesn’t fix your issue, what happens if you directly run `/Users/lixinxing/sourcekite/.build/x86_64-apple-macosx10.10/release/sourcekite`?

What happens if you run
