### ISSUE TITLE
Crash server startup

### ISSUE THREAD

**Issue by jonasandero** [vknabel/vscode-swift-development-environment#58]
Just built and installed sourcekit-lsp from source using swift 5.1. Configured the extension and it starts without error. Installed "Maintained Swift Development Environment" version 2.8.1 from marketplace. When I open a swift file, the server crashes with:

```Debugger listening on ws://127.0.0.1:6004/a4d80063-df59-4a20-a0a3-e514de6b6a35
For help, see: https://nodejs.org/en/docs/inspector
[Error - 10:42:55 PM] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'on' of undefined
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn . EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Info  - 10:42:55 PM] Connection to server got closed. Server will restart.
Debugger listening on ws://127.0.0.1:6004/671b3210-b21f-411a-a5ca-4fd5c74ceb90
For help, see: https://nodejs.org/en/docs/inspector
[Error - 10:42:55 PM] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'on' of undefined
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn . EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Info  - 10:42:55 PM] Connection to server got closed. Server will restart.
Debugger listening on ws://127.0.0.1:6004/485f2fe6-007d-4cd8-b67a-69ec578c43bd
For help, see: https://nodejs.org/en/docs/inspector
[Error - 10:42:55 PM] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'on' of undefined
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn . EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Info  - 10:42:55 PM] Connection to server got closed. Server will restart.
Debugger listening on ws://127.0.0.1:6004/9533fe61-8b3a-463c-aa75-e3f93a776fb4
For help, see: https://nodejs.org/en/docs/inspector
[Error - 10:42:55 PM] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'on' of undefined
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn . EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Info  - 10:42:55 PM] Connection to server got closed. Server will restart.
Debugger listening on ws://127.0.0.1:6004/0852ee82-1081-4a34-89c0-492d675eb4dd
For help, see: https://nodejs.org/en/docs/inspector
[Error - 10:42:56 PM] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'on' of undefined
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn . EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Error - 10:42:56 PM] Connection to server got closed. Server will not be restarted.
```

Ideas?

**Comment by jonasandero** [comment]
Doh, didn't read the instructions - forgot to set 

 "sde.languageServerMode": "sourcekit-lsp"
