### ISSUE TITLE
Crashing and using wrong source*

### ISSUE THREAD

**Issue by rex-remind101** [vknabel/vscode-swift-development-environment#74]
Settings:
```
"sde.languageservermode": "sourcekit-lsp",
  "sourcekit-lsp.serverPath": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/sourcekit-lsp",
  "sourcekit-lsp.toolchainPath": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain"
```

Output:
```
Debugger listening on ws://127.0.0.1:6004/fd7064ac-7a84-4ffa-83a5-0ff80acc966f
For help, see: https://nodejs.org/en/docs/inspector
/Users/Rex/.vscode/extensions/vknabel.vscode-swift-development-environment-2.10.0/out/src/server/sourcekites.js:54
        throw err;
        ^

Error: spawn . EACCES
    at Process.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn .',
  path: '.',
  spawnargs: []
}
[Info  - 5:28:11 PM] Connection to server got closed. Server will restart.
Debugger listening on ws://127.0.0.1:6004/e67b887f-af7b-47ad-b873-d0a0f211d452
For help, see: https://nodejs.org/en/docs/inspector
/Users/Rex/.vscode/extensions/vknabel.vscode-swift-development-environment-2.10.0/out/src/server/sourcekites.js:54
        throw err;
        ^

Error: spawn . EACCES
    at Process.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn .',
  path: '.',
  spawnargs: []
}
[Info  - 5:28:11 PM] Connection to server got closed. Server will restart.
Debugger listening on ws://127.0.0.1:6004/a868eb39-5dd0-4e3b-b5d1-8d97cfb8b62a
For help, see: https://nodejs.org/en/docs/inspector
/Users/Rex/.vscode/extensions/vknabel.vscode-swift-development-environment-2.10.0/out/src/server/sourcekites.js:54
        throw err;
        ^

Error: spawn . EACCES
    at Process.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn .',
  path: '.',
  spawnargs: []
}
[Info  - 5:28:11 PM] Connection to server got closed. Server will restart.
Debugger listening on ws://127.0.0.1:6004/065c8984-37c7-4c21-a9aa-f364184035b7
For help, see: https://nodejs.org/en/docs/inspector
/Users/Rex/.vscode/extensions/vknabel.vscode-swift-development-environment-2.10.0/out/src/server/sourcekites.js:54
        throw err;
        ^

Error: spawn . EACCES
    at Process.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn .',
  path: '.',
  spawnargs: []
}
[Info  - 5:28:12 PM] Connection to server got closed. Server will restart.
Debugger listening on ws://127.0.0.1:6004/9f4f2989-4406-434f-a0bf-578d85358985
For help, see: https://nodejs.org/en/docs/inspector
/Users/Rex/.vscode/extensions/vknabel.vscode-swift-development-environment-2.10.0/out/src/server/sourcekites.js:54
        throw err;
        ^

Error: spawn . EACCES
    at Process.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn .',
  path: '.',
  spawnargs: []
}
[Error - 5:28:12 PM] Connection to server got closed. Server will not be restarted.
```

notice the `sourcekites` in there rather than `sourcekit-lsp`.

**Comment by vknabel** [comment]
Hi @rex-remind101.

First of all: thanks for your report!
I currently don't have the time to have a deep look on this, but as a wild guess:
Does the error still persist after changing `sde.languageservermode` to `sde.languageServerMode` and a restart of vscode?

**Comment by tamc** [comment]
I hit the same area, and fixing the case of sde.languageServerMode fixed it. Thank you!

**Comment by vknabel** [comment]
Thanks for your feedback!
