### ISSUE TITLE
Connection to server got closed. Server will restart.

### ISSUE THREAD

**Issue by artemkalinovsky** [vknabel/vscode-swift-development-environment#81]
Got this error every time I open project:
```
Debugger listening on ws://127.0.0.1:6004/04ca5619-d706-4bd7-9711-8cd6ef959849
For help, see: https://nodejs.org/en/docs/inspector
/Users/artemkalinovsky/.vscode/extensions/vknabel.vscode-swift-development-environment-2.10.1/out/src/server/sourcekites.js:54
        throw err;
        ^

Error: spawn . EACCES
    at Process.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn .',
  path: '.',
  spawnargs: []
}
[Error - 2:21:23 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by vknabel** [comment]
Hi @artemkalinovsky!
Have you followed the installation instructions? https://github.com/vknabel/vscode-swift-development-environment#installation

This extension requires at least one additional tool.
Also check that your paths are configured correctly (especially for typos and spaces).

**Comment by artemkalinovsky** [comment]
Hi,

I checked my settings, and now I see this error:

```
Error: command 'semantic.refactor.command' already exists
	at _.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:693:559)
	at Object.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:988:219)
	at ExecuteCommandFeature.register (/Users/artemkalinovsky/.vscode/extensions/unpublished.sourcekit-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:1501:53)
	at ExecuteCommandFeature.initialize (/Users/artemkalinovsky/.vscode/extensions/unpublished.sourcekit-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:1491:14)
	at LanguageClient.initializeFeatures (/Users/artemkalinovsky/.vscode/extensions/unpublished.sourcekit-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:2168:21)
	at /Users/artemkalinovsky/.vscode/extensions/unpublished.sourcekit-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:1888:18
```

**Comment by artemkalinovsky** [comment]
Aha, according to last string in error log, I have active https://github.com/apple/sourcekit-lsp extension.
After I've disabled it, all errors disappeared.
